name: Rust

on:
  push:
    branches: [ main ]
    paths:
    - rustsaml/**
    - .github/workflows/restsaml.yml    
  pull_request:
    branches: [ main ]
    paths:
    - rustsaml/**
    - .github/workflows/rustsaml.yml    

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: rustsaml
    - name: Run tests
      run: cargo test --verbose
      working-directory: rustsaml
