name: Rustsaml

on:
  push:
    branches: [ main ]
    paths:
    - rustsaml/**
    - .github/workflows/rustsaml.yml    
  pull_request:
    branches: [ main ]
    paths:
    - rustsaml/**
    - .github/workflows/rustsaml.yml    

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: rustsaml
    - name: Run tests
      run: cargo test --verbose
      working-directory: rustsaml
